### ISSUE TITLE
flag -K -

### ISSUE THREAD

**Issue by cmsethi** [SP4RKiOP/AutoIPV6forDuckDNS#1]
Thanks for making the script.
Just curious to understand why (( -K - ) after the "utoipv6duckdns.log -K -" ? 
I saw one or two more scripts on StackOverflow without the " -K - " 
Your explanation will be appreciated
Thanks

**Comment by sp4rkiop** [comment]
Glad it helped you.

While i was creating the script to check the curl log i used the -k (with path to log file) to check the output. but i think i may had pasted the path to file 2 times and forgot to remove the flag while removing the path.

[i have updated it anyways.](https://github.com/SP4RKiOP/AutoIPV6forDuckDNS/commit/6c019e64eac281d4bed64102add45adb9f0be1b8)
